#!/bin/bash

. ./build_info

if [[ -z $DOCKER_REPO || -z $DOCKER_TAG ]]; then
    echo "You need to set \$DOCKER_REPO and \$DOCKER_TAG in build_info."
    exit 1
fi

if docker images $DOCKER_REPO | awk '{print $2}' | grep -q $DOCKER_TAG; then
    echo "Image $DOCKER_REPO:$DOCKER_TAG already exists."
    echo "Please specify a diffrent tag in build_info."
    exit 1
fi

echo "Building an image $DOCKER_REPO:$DOCKER_TAG..."
docker build -t $DOCKER_REPO:$DOCKER_TAG .
rc=$?

if [[ $rc -eq 0 ]]; then
    echo "Build succeeded. Your change will be committed."
    echo ""
    exit 0
else
    echo "Build failed. Your change won't be committed."
    echo ""
    exit 1
fi
